name: socksget

on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 3 * * *"

  
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3.5.2
    
    - name: Install Python
      uses: actions/setup-python@v4.6.0
          
    - name: RunPython
      run: |
        python Socks/get.py
        

      
    - name: write
      run: |                 
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git pull origin main
        git add -A
        git commit -m "Automatic update"
        git push
